let formatterVal = {
  "yesOrNo":[{"code":"1", "text": "是"}, {"code":"0", "text": "否"}],
  "BZFS": [{"code":"01", "text": "常规"}, {"code":"02", "text": "地下"},{"code":"03", "text": "半地下"}],
  "DQTZ": [{"code":"01", "text": "市中心区"}, {"code":"02", "text": "市区"},{"code":"03", "text": "城镇"},{"code":"04", "text": "县城区"},{"code":"05", "text": "农村"},{"code":"06", "text": "乡镇"},{"code":"07", "text": "农牧区"}],
  "DYDJMC": [{"code":"22", "text": "交流10kV"}, {"code":"25", "text": "交流35kV"}],
  "DZLX": [
    {"code":"zf01", "text": "变电站"},
    {"code":"zf02", "text": "换流站"},
    {"code":"zf03", "text": "串补站"},
    {"code":"zf04", "text": "开关站"},
    {"code":"zf05", "text": "电厂"},
    {"code":"zf06", "text": "配电室"},
    {"code":"zf07", "text": "环网柜"},
    {"code":"zf08", "text": "箱式变电站"},
    {"code":"zf09", "text": "电缆分支箱"},
    {"code":"zf10", "text": "低压配电箱"},
    {"code":"zf11", "text": "低压配电箱"},
    {"code":"zf12", "text": "低压电缆分支箱"},
    {"code":"zf13", "text": "低压电缆终端箱"},
  ],
  "YXZT": [
    {"code":"31", "text": "现场留用"},
    {"code":"32", "text": "库存备用"},
    {"code":"20", "text": "在运"},
    {"code":"30", "text": "退役"},
    {"code":"40", "text": "报废"},
    {"code":"10", "text": "未投运"},
    {"code":"33", "text": "待报废"},
  ],
  "ZYFL": [
    {"code":"1", "text": "输电"},
    {"code":"2", "text": "变电"},
    {"code":"3", "text": "配电"},
  ],
  "ZCXZ": [
    {"code":"01", "text": "国家电网公司"},
    {"code":"02", "text": "分部"},
    {"code":"03", "text": "省（直辖市、自治区）公司"},
    {"code":"04", "text": "子公司"},
    {"code":"05", "text": "用户"},
  ],
  "SSDS": [
    {'code': '8a812897493378a00149567740676661', 'text': '上海电力公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP03', 'text': '市区供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP04', 'text': '市北供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP05', 'text': '市南供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP06', 'text': '浦东供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP07', 'text': '奉贤供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP08', 'text': '嘉定供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP09', 'text': '青浦供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP0A', 'text': '松江供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP0B', 'text': '金山供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP0D', 'text': '供电服务中心'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSP50', 'text': '检修公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSPHZ', 'text': '崇明供电公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFSPKZ', 'text': '长兴供电公司'},
  ],
  "WHBZ": [
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100015788', 'text': '测绘公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014351', 'text': '电缆数据输入组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014352', 'text': '电缆运检五班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018305', 'text': '闸电东海'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019643', 'text': '闵行（集团）分公司变电一班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100015066', 'text': '星冠'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014750', 'text': '华龙'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100020071', 'text': '乾雁'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014736', 'text': '志佳'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014659', 'text': '锦湾'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018988', 'text': '市南集团线缆施工1组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5631689', 'text': '华漕供电营业站'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019727', 'text': '中电建设'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100003979', 'text': '兆博'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016334', 'text': '为民'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014754', 'text': '七宝'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018948', 'text': '惠盟'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5632588', 'text': '莘电班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019783', 'text': '永磐'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014757', 'text': '腾清'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100002133', 'text': '滨海'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562330', 'text': '集团公司-线路检修班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018993', 'text': '市南集团线缆施工6组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019005', 'text': '市南电力工程-工程公司兴铨班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016220', 'text': '中南'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5631690', 'text': '梅陇供电营业站'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5631692', 'text': '颛桥供电营业站'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5631693', 'text': '七宝供电营业站'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5632587', 'text': '鲁汇班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5632589', 'text': '伟达班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100020220', 'text': '久隆市区鑫电班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016290', 'text': '盛缆'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016336', 'text': '大华电器'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016442', 'text': '沪总'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100002901', 'text': '莘欣班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100020017', 'text': '变电(配电)二次运检二班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100020033', 'text': '南阳班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100020038', 'text': '永源'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018991', 'text': '市南集团线缆施工4组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018992', 'text': '市南集团线缆施工5组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018995', 'text': '市南集团线缆施工8组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018998', 'text': '市南集团线缆施工11组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019000', 'text': '市南集团线缆施工12组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019001', 'text': '市南电力工程-工程公司启东班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019003', 'text': '市南电力工程-工程公司莘电班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019004', 'text': '市南电力工程-工程公司七宝班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100020238', 'text': '新茸'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018997', 'text': '市南集团线缆施工10组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5613742', 'text': '集团公司-线缆工程组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018990', 'text': '市南集团线缆施工3组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100003154', 'text': '继保'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5613951', 'text': '自动化组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5631671', 'text': '综合组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5631691', 'text': '杜行供电营业站'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562345', 'text': '客户服务组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5634000', 'text': '工询'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014354', 'text': '电缆运检二班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018498', 'text': '配网抢修指挥中心'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562342', 'text': '线路运检组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016931', 'text': '恰尔斯'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017011', 'text': '变电中心三站'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017053', 'text': '明昕电力'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017169', 'text': '银电电力'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017170', 'text': '银溢电器'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562326', 'text': '变电修试一组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562334', 'text': '线路操作一组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562337', 'text': '配电运维组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562338', 'text': '带电作业组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562340', 'text': '变电(配电)二次运检一班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019792', 'text': '久隆市区启东班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562566', 'text': '变电中心一站'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100004910', 'text': '申新班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017473', 'text': '盛隆'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019383', 'text': '茗川班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017913', 'text': '兴铨'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF6734547', 'text': '市南电力工程有限公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF6739821', 'text': '市南通信公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5632590', 'text': '启东班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5613811', 'text': '电缆运检三班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5614052', 'text': '装表接电组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5630753', 'text': '营销数据录入组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5631669', 'text': '调度控制组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017146', 'text': '久隆'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100002180', 'text': '上海送变电'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100002597', 'text': '华东送变电'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014578', 'text': '鲁汇'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017540', 'text': '航讯'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014758', 'text': '青浦香花桥'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016782', 'text': '工程公司电缆班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100003165', 'text': '电力实业'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100003153', 'text': '运方'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562319', 'text': '（集团）分公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFFF562328', 'text': '集团公司-工程管理部'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014593', 'text': '莘电'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014637', 'text': '华胜建设'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014647', 'text': '林江'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014653', 'text': '晓宇'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014665', 'text': '华群'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014696', 'text': '华杰'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014723', 'text': '南华兰陵'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014731', 'text': '华盛安装'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5613815', 'text': '变电修试二组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5633445', 'text': '市南客户中心'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019838', 'text': '市南电力工程-工程公司南华兰陵'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100020037', 'text': '市南电力工程-工程公司南阳班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014742', 'text': '中能'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014747', 'text': '承广'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014751', 'text': '华南'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014752', 'text': '华威'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014755', 'text': '电院'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014756', 'text': '莘欣'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014831', 'text': '启东三'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014604', 'text': '大华工程'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014748', 'text': '电力教培'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100015064', 'text': '宏泰'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100015336', 'text': '施工单位'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100015435', 'text': '工程公司-电缆工程部'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100015632', 'text': '新泰电力'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014621', 'text': '申新'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014708', 'text': '华贻'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019837', 'text': '市南电力工程-工程公司承广'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019941', 'text': '市南电力工程-工程公司恰尔斯'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017091', 'text': '上海京东电力设备安装'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100000445', 'text': '项目部'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014353', 'text': '电缆运检四班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014355', 'text': '电缆运检一班'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017010', 'text': '线路操作二组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019839', 'text': '市南电力工程-工程公司华群'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100017762', 'text': '利源'},
    {'code': '8a0396d44b5ed7a0014ccb8719f76386', 'text': '市南外包班组'},
    {'code': '8a0396d44b5ed7a0014cfef661b87412', 'text': '工程公司班组'},
    {'code': 'ff808081531865f901545baabd421289', 'text': '神洁'},
    {'code': '8a0396d45318629e0154944ba5272cbf', 'text': '冲佳'},
    {'code': 'ff808081531865f90154944c16d03c06', 'text': '润育'},
    {'code': 'ff808081531865f90154cc1a062b592a', 'text': '运检临时帐号'},
    {'code': '8a0396d45318629e015556e151110d3d', 'text': '茗川'},
    {'code': 'ff808081531865f90157a867cff3708d', 'text': '胜百'},
    {'code': 'ff808081531865f90157e0d12a2444e3', 'text': '昀升班'},
    {'code': 'ff808081531865f901584d2e84c526da', 'text': '华瑞'},
    {'code': 'ff808081584f0c6501586bd6fecf1c62', 'text': '芜湖华瑞'},
    {'code': 'ff80808158af766f0158b8ce041105af', 'text': '临时'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018996', 'text': '市南集团线缆施工9组'},
    {'code': 'ff808081592c8a1c015a69ae0f110ac3', 'text': '上海宏泰水电安装工程有限公司'},
    {'code': 'ff808081592c8a1c015bae1316804fd7', 'text': '配电运维二组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014749', 'text': '飞弘'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100015136', 'text': '鑫电'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016335', 'text': '振建'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5632586', 'text': '七宝班'},
    {'code': 'ff8080814b5ed543014b7d5206bf0eaa', 'text': '隆电'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100016355', 'text': '用电信息采集组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100019002', 'text': '市南电力工程-工程公司鲁汇班'},
    {'code': '8a0396d45de5b891015e1707cc8a2ca2', 'text': '上海舜韬电力工程有限公司'},
    {'code': 'ff8080815eadf4f5015f5162d46f5feb', 'text': '上海新泰建筑工程有限公司'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFFFF5633757', 'text': '变电中心二站'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100002596', 'text': '海安'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100018989', 'text': '市南集团线缆施工2组'},
    {'code': 'FFFFFFFFFFFFFFFFFFFFFFF100014753', 'text': '闵行'},
    {'code': '8a0396d45de5b8910160b9afad6330ba', 'text': '上海电力实业有限公司'},
    {'code': '8a03e1ac6742acd50167a5424f3064f9', 'text': '休元'},
    {'code': '8a03e1ac6b506880016c41f13ad95797', 'text': '上海盛通电力设计有限公司'},
  ],
  "JYJZ": [
    {'code': '1', 'text': '油浸'},
    {'code': '2', 'text': 'SF6'},
    {'code': '3', 'text': '干式'},
    {'code': '4', 'text': '环氧树脂'},
    {'code': '5', 'text': '光电式'},
    {'code': '6', 'text': '空气'},
    {'code': '7', 'text': '真空'},
    {'code': '8', 'text': '氮气（N2）'},
  ],
  "ZYCD": [
    {"code":"1", "text": "一般"},
    {"code":"2", "text": "重要"},
    {"code":"3", "text": "特别重要"},
  ],
  "QDLX": [
    {"code":"1", "text": "间隔"},
    {"code":"2", "text": "杆塔"},
    {"code":"3", "text": "电缆T接头"},
    {"code":"4", "text": "电缆小间"},
    {"code":"5", "text": "构架"},
    {"code":"6", "text": "用户站"},
    {"code":"7", "text": "虚拟电源点"},
  ],
  "JSFS": [
    {"code":"1", "text": "架空"},
    {"code":"2", "text": "混合"},
    {"code":"3", "text": "电缆"},
  ],
  "XLXZ": [
    {"code":"1", "text": "架空"},
    {"code":"2", "text": "支线"},
    {"code":"3", "text": "分支线"},
    {"code":"4", "text": "分段线路"},
    {"code":"5", "text": "馈线"},
  ]
};

let tab1GroupHeaders = [
  {'key': 'OBJ_ID', 'name': '设备id','minWidth': '200'},
  {'key': 'PBTS', 'name': '配变台数'},
  {'key': 'PBZRL', 'name': '配变总容量','minWidth': '100'},
  {'key': 'BZFS', 'name': '布置方式', 'fKey': 'BZFS'},
  {'key': 'SFDXZ', 'name': '是否地下站', 'fKey': 'yesOrNo','minWidth': '100'},
  {'key': 'DQTZ', 'name': '地区特征', 'fKey': 'DQTZ'},
  {'key': 'DYDJ', 'name': '电压等级'},
  {'key': 'DYDJMC', 'name': '电压等级名称', 'fKey': 'DYDJMC','minWidth': '150'},
  {'key': 'DZLX', 'name': '电站类型', 'fKey': 'DZLX'},
  {'key': 'SFDW', 'name': '是否代维', 'fKey': 'yesOrNo'},
  {'key': 'SFNW', 'name': '是否农网', 'fKey': 'yesOrNo'},
  {'key': 'SSDS', 'name': '所属地市', 'fKey': 'SSDS','minWidth': '150'},
  {'key': 'SSDSMC', 'name': '所属地市名称','minWidth': '200'},
  {'key': 'TYRQ', 'name': '投运日期'},
  {'key': 'WHBZ', 'name': '维护班组', 'fKey': 'WHBZ', 'minWidth': '100'},
  {'key': 'WHBZMC', 'name': '维护班组名称','minWidth': '150'},
  {'key': 'YWDW', 'name': '运维单位', 'fKey': 'SSDS','minWidth': '150'},
  {'key': 'YWDWMC', 'name': '运维单位名称','minWidth': '150'},
  {'key': 'YXBH', 'name': '运行编号'},
  {'key': 'YXZT', 'name': '运行状态', 'fKey': 'YXZT'},
  {'key': 'ZCDW', 'name': '资产单位'},
  {'key': 'ZCDWMC', 'name': '资产单位名称','minWidth': '150'},
  {'key': 'ZCXZ', 'name': '资产性质', 'fKey': 'ZCXZ'},
  {'key': 'ZYFL', 'name': '专业分类', 'fKey': 'ZYFL'},
  {'key': 'ZZ', 'name': '站址'},
  {'key': 'BYJCXJGS', 'name': '备用进出线间隔数','minWidth': '200'},
  {'key': 'BZ', 'name': '备注'}
];

let tab2GroupHeaders = [
  {'key': 'OBJ_ID', 'name': '设备id','minWidth': '200'},
  {'key': 'CCBH', 'name': '出厂编号'},
  {'key': 'CCRQ', 'name': '出厂日期'},
  {'key': 'DQTZ', 'name': '地区特征', 'fKey': 'DQTZ'},
  {'key': 'DYCEDDL', 'name': '低压侧额定电流'},
  {'key': 'DYDJ', 'name': '电压等级'},
  {'key': 'DYDJMC', 'name': '电压等级名称', 'fKey': 'DYDJMC'},
  {'key': 'EDRL', 'name': '额定容量'},
  {'key': 'JYJZ', 'name': '绝缘介质', 'fKey': 'JYJZ'},
  {'key': 'SBMC', 'name': '设备名称'},
  {'key': 'SCCJ', 'name': '生产厂家'},
  {'key': 'SFDW', 'name': '是否代维', 'fKey': 'yesOrNo'},
  {'key': 'SFFJB', 'name': '是否非晶变', 'fKey': 'yesOrNo'},
  {'key': 'SFNW', 'name': '是否农网', 'fKey': 'yesOrNo'},
  {'key': 'SSDS', 'name': '所属地市', 'fKey': 'SSDS'},
  {'key': 'SSDSMC', 'name': '所属地市名称'},
  {'key': 'SSGT', 'name': '所属杆塔'},
  {'key': 'SYXZ', 'name': '使用性质'},
  {'key': 'TYRQ', 'name': '投运日期'},
  {'key': 'XH', 'name': '型号'},
  {'key': 'YWDW', 'name': '运维单位', 'fKey': 'SSDS'},
  {'key': 'YWDWMC', 'name': '运维单位名称'},
  {'key': 'YXZT', 'name': '运行状态', 'fKey': 'YXZT'},
  {'key': 'ZCDW', 'name': '资产单位'},
  {'key': 'ZCDWMC', 'name': '资产单位名称'},
  {'key': 'ZCXZ', 'name': '资产性质', 'fKey': 'ZCXZ'},
  {'key': 'ZYCD', 'name': '重要程度', 'fKey': 'ZYCD'},
  {'key': 'ZYFL', 'name': '专业分类', 'fKey': 'ZYFL'},
  {'key': 'ZXMC', 'name': '主线名称'},
  {'key': 'BZ', 'name': '备注'}
];
let tab2GroupHeaders2 = [
  {'key': 'OBJ_ID', 'name': '设备id','minWidth': '200'},
  {'key': 'CCBH', 'name': '出厂编号'},
  {'key': 'CCRQ', 'name': '出厂日期'},
  {'key': 'DQTZ', 'name': '地区特征', 'fKey': 'DQTZ'},
  {'key': 'DYCEDDL', 'name': '低压侧额定电流'},
  {'key': 'DYDJ', 'name': '电压等级'},
  {'key': 'EDRL', 'name': '额定容量'},
  {'key': 'JYJZ', 'name': '绝缘介质', 'fKey': 'JYJZ'},
  {'key': 'SBMC', 'name': '设备名称'},
  {'key': 'SCCJ', 'name': '生产厂家'},
  {'key': 'SFDW', 'name': '是否代维', 'fKey': 'yesOrNo'},
  {'key': 'SFFJB', 'name': '是否非晶变', 'fKey': 'yesOrNo'},
  {'key': 'SFNW', 'name': '是否农网', 'fKey': 'yesOrNo'},
  {'key': 'SSDS', 'name': '所属地市', 'fKey': 'SSDS'},
  {'key': 'SSDSMC', 'name': '所属地市名称'},
  {'key': 'SSZF', 'name': '所属站房'},
  {'key': 'SYXZ', 'name': '使用性质'},
  {'key': 'TYRQ', 'name': '投运日期'},
  {'key': 'XH', 'name': '型号'},
  {'key': 'YWDW', 'name': '运维单位', 'fKey': 'SSDS'},
  {'key': 'YWDWMC', 'name': '运维单位名称'},
  {'key': 'YXZT', 'name': '运行状态', 'fKey': 'YXZT'},
  {'key': 'ZCDW', 'name': '资产单位'},
  {'key': 'ZCDWMC', 'name': '资产单位名称'},
  {'key': 'ZCXZ', 'name': '资产性质', 'fKey': 'ZCXZ'},
  {'key': 'ZYCD', 'name': '重要程度', 'fKey': 'ZYCD'},
  {'key': 'ZYFL', 'name': '专业分类', 'fKey': 'ZYFL'},
  {'key': 'BZ', 'name': '备注'},

];

let tab3GroupHeaders = [
  {'key': 'OBJ_ID', 'name': '设备id','minWidth': '200'},
  {'key': 'XLMC', 'name': '线路名称'},
  {'key': 'DYDJ', 'name': '电压等级'},
  {'key': 'DYDJMC', 'name': '电压等级名称', 'fKey': 'DYDJMC'},
  {'key': 'YWDW', 'name': '运维单位', 'fKey': 'SSDS'},
  {'key': 'YWDWMC', 'name': '运维单位名称'},
  {'key': 'SSDD', 'name': '所属调度'},
  {'key': 'DDDWMC', 'name': '调度单位名称'},
  {'key': 'YXZT', 'name': '运行状态', 'fKey': 'YXZT'},
  {'key': 'QDDZ', 'name': '起点电站'},
  {'key': 'QDDZMC', 'name': '起点电站名称'},
  {'key': 'QDLX', 'name': '起点类型', 'fKey': 'QDLX'},
  {'key': 'TYRQ', 'name': '投运日期'},
  {'key': 'JSFS', 'name': '架设方式', 'fKey': 'JSFS'},
  {'key': 'XLXZ', 'name': '线路性质', 'fKey': 'XLXZ'},
  {'key': 'SFDW', 'name': '是否代维', 'fKey': 'yesOrNo'},
  {'key': 'XLZCD', 'name': '线路总长度'},
  {'key': 'JKXLCD', 'name': '架空线路长度'},
  {'key': 'DLXLCD', 'name': '电缆线路长度'},
  {'key': 'ZCXZ', 'name': '资产性质'},
  {'key': 'ZYCD', 'name': '重要程度', 'fKey': 'ZYCD'},
  {'key': 'SSZX', 'name': '所属主线'},
  {'key': 'ZCDW', 'name': '资产单位'},
  {'key': 'ZCDWMC', 'name': '资产单位名称'},
  {'key': 'SSDS', 'name': '所属地市', 'fKey': 'SSDS'},
  {'key': 'SSDSMC', 'name': '所属地市名称'},
  {'key': 'WHBZ', 'name': '维护班组', 'fKey': 'SSDS'},
  {'key': 'WHBZMC', 'name': '维护班组名称'},
  {'key': 'QDWZ', 'name': '起点位置'},
  {'key': 'QDWZMC', 'name': '起点位置名称'},
  {'key': 'ZDWZ', 'name': '终点位置'},
  {'key': 'ZDWZMC', 'name': '终点位置名称'},
  {'key': 'SFNW', 'name': '是否农网', 'fKey': 'yesOrNo'},
  {'key': 'DQTZ', 'name': '地区特征', 'fKey': 'DQTZ'},
  {'key': 'SSKX', 'name': '所属馈线'},
  {'key': 'ZYFL', 'name': '专业分类', 'fKey': 'ZYFL'},
  {'key': 'BZ', 'name': '备注'},
]

let tab3GroupHeaders3 = [
  {'key': 'ORG_NO', 'name': '表箱产权归属单位','minWidth': '200'},
  {'key': 'ASSET_NO', 'name': '资产、局编号'},
  {'key': 'BAR_CODE', 'name': '条形码'},
  {'key': 'MADE_DATE', 'name': '生产日期'},
  {'key': 'DOC_CREATE_DATE', 'name': '建档日期'},
]


export {
  formatterVal,
  tab1GroupHeaders,
  tab2GroupHeaders,
  tab2GroupHeaders2,
  tab3GroupHeaders,
  tab3GroupHeaders3
}
